=== fielddaylab/coolIt/server/MaterialProperties/Schema/MaterialCurveDescriptions.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio (http://www.liquid-technologies.com)-->
<xs:schema xmlns:doc="http://example.org.doc" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="materialType">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        <doc:description xmlns:doc="http://example.org.doc">
					This element represents a single material.
				</doc:description>
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="name">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string" />
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="ID" type="xs:positiveInteger" />
      <xs:element minOccurs="0" name="descriptor" type="xs:string" />
      <xs:element name="price">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            <doc:description xmlns:doc="http://example.org.doc">
							The price is in U.S. dollars per unit.  The unit is defined below.
						</doc:description>
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:decimal">
              <xs:attribute name="priceUnit" type="priceUnitType" use="required" />
              <xs:attribute name="reference" type="xs:anyURI" use="optional" />
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="density">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            <doc:description xmlns:doc="http://example.org.doc">
							Density in grams / cm ^ 3.
						</doc:description>
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:double">
              <xs:attribute name="reference" type="xs:anyURI" use="optional" />
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="tensileStrength">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            <doc:description xmlns:doc="http://example.org.doc">
							Tensile strength in MPa.
						</doc:description>
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:double">
              <xs:attribute name="reference" type="xs:anyURI" use="optional" />
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="compressionStrength">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            <doc:description xmlns:doc="http://example.org.doc">
							Compression strength in MPa.
						</doc:description>
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:double">
              <xs:attribute name="reference" type="xs:anyURI" use="optional" />
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="youngsModulus">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            <doc:description xmlns:doc="http://example.org.doc">
							Young's modulus in GPa.
						</doc:description>
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:double">
              <xs:attribute name="reference" type="xs:anyURI" use="optional" />
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element minOccurs="0" name="shearStrength">
        <xs:annotation>
          <xs:documentation xml:lang="en">
            <doc:description xmlns:doc="http://example.org.doc">
							Shear strength in MPa.
						</doc:description>
          </xs:documentation>
        </xs:annotation>
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:double">
              <xs:attribute name="reference" type="xs:anyURI" use="optional" />
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
      <xs:element name="thermalConductivity" type="parameterizedCurveType">
        <xs:annotation>
          <xs:documentation>Thermal conductivity in Watts / meter Kelvin (W/mK)</xs:documentation>
        </xs:annotation>
      </xs:element>
      <xs:element name="integratedThermalConductivity" type="parameterizedCurveType">
        <xs:annotation>
          <xs:documentation>Integrated thermal conductivity in Watts / meter (W/m).  These are all specified with respect to 300 deg K.</xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="parameterizedCurveType">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        <doc:description xmlns:doc="http://example.org.doc">
					This element represents a mathematical curve which is described by a set of
					parameters to an equation.  The type of the equation to be used to generate the
					curve as well as minimum and maximum temperatures (deg K) for which this equation
					is valid must be supplied.
				</doc:description>
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="equationType" type="equationType" />
      <xs:element name="minTemp" type="xs:nonNegativeInteger" />
      <xs:element name="maxTemp" type="xs:nonNegativeInteger" />
      <xs:element maxOccurs="unbounded" name="coefficient" type="xs:double" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="priceScalingType">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        <doc:description xmlns:doc="http://example.org.doc">
					This element represents price scaling which should be applied to the entire set
					of materials.  The scaled price equals (price + offset) * scalingFactor.
				</doc:description>
      </xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="offset" type="xs:double" />
      <xs:element name="scalingFactor" type="xs:double" />
    </xs:sequence>
  </xs:complexType>
  <xs:simpleType name="priceUnitType">
    <xs:restriction base="xs:token">
      <xs:enumeration value="kg" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="equationType">
    <xs:annotation>
      <xs:documentation>Equation types:

type1: y = 10^(a+b(log10T) + c(log10T)^2 + d(log10T)^3 + e(log10T)^4 + f(log10T)^5 + g(log10T)^6 + h(log10T)^7 + i(log10T)^8) 

polyLn: y=a+blnx+c(lnx)^2+d(lnx)^3+e(lnx)^4+f(lnx)^5+g(lnx)^6+h(lnx)^7+i(lnx)^8+j(lnx)^9+k(lnx)^(10)

polyFit: y=a+bx+cx^2+dx^3+ex^4+fx^5+gx^6+hx^7+ix^8+jx^9+kx^10

</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:token">
      <xs:enumeration value="type1" />
      <xs:enumeration value="polyLn" />
      <xs:enumeration value="polyFit" />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="materialData">
    <xs:annotation>
      <xs:documentation xml:lang="en">
        <doc:description xmlns:doc="http://example.org.doc">
					This schema represents the collection of materials used in the educational
					game "CoolIt".
				</doc:description>
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" name="priceScalingInfo" type="priceScalingType" />
        <xs:element name="materials">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="material" type="materialType" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== fielddaylab/coolIt/server/MaterialProperties/Data/MaterialCurves.xml
<?xml version="1.0" encoding="UTF-8"?>
<materialData xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:C:\Users\mike\Documents\Visual Studio 2005\Projects\CoolIt\MaterialProperties\Schema\MaterialCurveDescriptions.xsd">
	<priceScalingInfo>
		<offset>1</offset>
		<!--  <scalingFactor>59.21</scalingFactor>  -->
		<scalingFactor>50.0</scalingFactor>
	</priceScalingInfo>
	<materials>
		<material>
			<name>Aluminum 1100</name>
			<ID>1</ID>
			<descriptor>UNS A91100</descriptor>
			<price priceUnit="kg" reference="http://www.metalprices.com/FreeSite/Charts/al_lme_charts.html?weight=lb#Chart1">1.9</price>
			<density>2.71</density>
			<tensileStrength>145</tensileStrength>
			<youngsModulus reference="http://en.wikipedia.org/wiki/Young%27s_modulus">69</youngsModulus>
			<shearStrength>62.1</shearStrength>
			<thermalConductivity>
				<equationType>type1</equationType>
				<minTemp>4</minTemp>
				<maxTemp>300</maxTemp>
				<coefficient>23.39172</coefficient>
				<coefficient>-148.5733</coefficient>
				<coefficient>422.1917</coefficient>
				<coefficient>-653.6664</coefficient>
				<coefficient>607.0402</coefficient>
				<coefficient>-346.152</coefficient>
				<coefficient>118.4276</coefficient>
				<coefficient>-22.2781</coefficient>
				<coefficient>1.770187</coefficient>
			</thermalConductivity>
			<integratedThermalConductivity>
				<equationType>polyLn</equationType>
				<minTemp>4</minTemp>
				<maxTemp>300</maxTemp>
				<coefficient>413249.711843258</coefficient>
				<coefficient>-1570974.16566984</coefficient>
				<coefficient>2607191.42161379</coefficient>
				<coefficient>-2484807.905</coefficient>
				<coefficient>1504289.12307285</coefficient>
				<coefficient>-603796.15885904</coefficient>
				<coefficient>162609.092299182</coefficient>
				<coefficient>-29006.5454679825</coefficient>
				<coefficient>3282.34939895406</coefficient>
				<coefficient>-213.093467920061</coefficient>
				<coefficient>6.04004120258886</coefficient>
			</integratedThermalConductivity>
		</material>
		<material>
			<name>Aluminum 3003F</name>
			<ID>2</ID>
			<descriptor>UNS A93003</descriptor>
			<price priceUnit="kg">1.9</price>
			<density>2.73</density>
			<tensileStrength>179</tensileStrength>
			<thermalConductivity>
				<equationType>type1</equationType>
				<minTemp>1</minTemp>
				<maxTemp>300</maxTemp>
				<coefficient>0.63736</coefficient>
				<coefficient>-1.1437</coefficient>
				<coefficient>7.4624</coefficient>
				<coefficient>-12.6905</coefficient>
				<coefficient>11.9165</coefficient>
				<coefficient>-6.18721</coefficient>
				<coefficient>1.63939</coefficient>
				<coefficient>-0.172667</coefficient>
				<coefficient>0</coefficient>
			</thermalConductivity>
			<integratedThermalConductivity>
				<equationType>polyLn</equationType>
				<minTemp>4</minTemp>
				<maxTemp>300</maxTemp>
				<coefficient>-1560.631231</coefficient>
				<coefficient>10158.61649</coefficient>
				<coefficient>-26183.16665</coefficient>
				<coefficient>35910.25844</coefficient>
				<coefficient>-29480.15423</coefficient>
				<coefficient>15335.66629</coefficient>
				<coefficient>-5167.390917</coefficient>
				<coefficient>1121.64598</coefficient>
				<coefficient>-150.8313119</coefficient>
				<coefficient>11.40582004</coefficient>
				<coefficient>-0.369799133</coefficient>
			</integratedThermalConductivity>
		</material>
		<material>
			<name>Aluminum 5083F-0</name>
			<ID>3</ID>
			<descriptor>UNS A95083</descriptor>
			<price priceUnit="kg">1.9</price>
			<density>2.66</density>
			<tensileStrength>290</tensileStrength>
			<thermalConductivity>
				<equationType>type1</equationType>
				<minTemp>1</minTemp>
				<maxTemp>300</maxTemp>
				<coefficient>-0.90933</coefficient>
				<coefficient>5.751</coefficient>
				<coefficient>-11.112</coefficient>
				<coefficient>13.612</coefficient>
				<coefficient>-9.3977</coefficient>
				<coefficient>3.6873</coefficient>
				<coefficient>-0.77295</coefficient>
				<coefficient>0.067336</coefficient>
				<coefficient>0</coefficient>
			</thermalConductivity>
			<integratedThermalConductivity>
				<equationType>polyLn</equationType>
				<minTemp>4</minTemp>
				<maxTemp>300</maxTemp>
				<coefficient>94.9080073477344</coefficient>
				<coefficient>-604.577654057284</coefficient>
				<coefficient>1510.44676856713</coefficient>
				<coefficient>-1991.21280821362</coefficient>
				<coefficient>1564.89515785713</coefficient>
				<coefficient>-774.613570214657</coefficient>
				<coefficient>247.448855436536</coefficient>
				<coefficient>-50.7124633392548</coefficient>
				<coefficient>6.43065757717741</coefficient>
				<coefficient>-0.456222594510606</coefficient>
				<coefficient>0.0142015603152395</coefficient>
			</integratedThermalConductivity>
		</material>
		<material>
			<name>Aluminum 6061 T6</name>
			<ID>4</ID>
			<price priceUnit="kg">1.9</price>
			<density>2.7</density>
			<tensileStrength>310</tensileStrength>
			<thermalConductivity>
				<equationType>type1</equationType>
				<minTemp>1</minTemp>
				<maxTemp>300</maxTemp>
				<coefficient>0.07981</coefficient>
				<coefficient>1.0957</coefficient>
				<coefficient>-0.07277</coefficient>
				<coefficient>0.08084</coefficient>
				<coefficient>0.02803</coefficient>
				<coefficient>-0.09464</coefficient>
				<coefficient>0.04179</coefficient>
				<coefficient>-0.00571</coefficient>
				<coefficient>0</coefficient>
			</thermalConductivity>
			<integratedThermalConductivity>
				<equationType>polyLn</equationType>
				<minTemp>4</minTemp>
				<maxTemp>300</maxTemp>
				<coefficient>-93.89503617</coefficient>
				<coefficient>603.1536047</coefficient>
				<coefficient>-1538.673341</coefficient>
				<coefficient>2100.84148</coefficient>
				<coefficient>-1721.2316</coefficient>
				<coefficient>899.7915027</coefficient>
				<coefficient>-306.8305306</coefficient>
				<coefficient>68.16816299</coefficient>
				<coefficient>-9.505149036</coefficient>
				<coefficient>0.76088691</coefficient>
				<coefficient>-0.026281191</coefficient>
			</integratedThermalConductivity>
		</material>
		<material>
			<name>Aluminum 6063 T5</name>
			<ID>5</ID>
			<price priceUnit="kg">1.9</price>
			<density>2.7</density>
			<tensileStrength>186</tensileStrength>
			<thermalConductivity>
				<equationType>type1</equationType>
				<minTemp>4</minTemp>
				<maxTemp>295</maxTemp>
				<coefficient>22.401433</coefficient>
				<coefficient>-141.13433</coefficient>
				<coefficient>394.95461</coefficient>
				<coefficient>-601.15377</coefficient>
				<coefficient>547.83202</coefficient>
				<coefficient>-305.99691</coefficient>
				<coefficient>102.38656</coefficient>
				<coefficient>-18.810237</coefficient>
				<coefficient>1.4576882</coefficient>
			</thermalConductivity>
			<integratedThermalConductivity>
				<equationType>polyLn</equationType>
				<minTemp>4</minTemp>
				<maxTemp>300</maxTemp>
				<coefficient>413249.7118</coefficient>
				<coefficient>-1570974.166</coefficient>
				<coefficient>2607191.422</coefficient>
				<coefficient>-2484807.905</coefficient>
				<coefficient>1504289.123</coefficient>
				<coefficient>-603796.1589</coefficient>
				<coefficient>162609.0923</coefficient>
				<coefficient>-29006.54547</coefficient>
				<coefficient>3282.349399</coefficient>
				<coefficient>-213.0934679</coefficient>
				<coefficient>6.040041203</coefficient>
			</integratedThermalConductivity>
		</material>
		<material>
			<name>Balsa 6</name>
			<ID>5</ID>
			<descriptor>6 lb/ft^3</descriptor>
			<price priceUnit="kg">2.83</price>
			<density>0.155</density>
			<tensileStrength>13.1</tensileStrength>
			<thermalConductivity>
				<equationType>type1</equationType>
				<minTemp>70</minTemp>
				<maxTemp>300</maxTemp>
				<coefficient>4172.447</coefficient>
				<coefficient>-11309.97</coefficient>
				<coefficient>12745.09</coefficient>
				<coefficient>-7647.584</coefficient>
				<coefficient>2577.309</coefficient>
				<coefficient>-462.538</coefficient>
				<coefficient>34.5351</coefficient>
				<coefficient>0</coefficient>
				<coefficient>0</coefficient>
			</thermalConductivity>
			<integratedThermalConductivity>
				<equationType>polyLn</equationType>
				<minTemp>88</minTemp>
				<maxTemp>300</maxTemp>
				<coefficient>555.6134475</coefficient>
				<coefficient>-1183.252032</coefficient>
				<coefficient>878.1477149</coefficient>
				<coefficient>-306.4615133</coefficient>
				<coefficient>51.69882033</coefficient>
				<coefficient>-4.244901383</coefficient>
				<coefficient>0.923056118</coefficient>
				<coefficient>-0.379862896</coefficient>
				<coefficient>0.072199696</coefficient>
				<coefficient>-0.006348567</coefficient>
				<coefficient>0.000217092</coefficient>
			</integratedThermalConductivity>
		</material>
		<material>
			<name>Balsa 11</name>
			<ID>6</ID>
			<descriptor>11 lb/ft^3</descriptor>
			<price priceUnit="kg">26</price>
			<density>0.24</density>
			<tensileStrength>22.9</tensileStrength>
			<thermalConductivity>
				<equationType>type1</equationType>
				<minTemp>75</minTemp>
				<maxTemp>300</maxTemp>
				<coefficient>4815.4</coefficient>
				<coefficient>-12969.63</coefficient>
				<coefficient>14520.76</coefficient>
				<coefficient>-8654.164</coefficient>
				<coefficient>2895.712</coefficient>
				<coefficient>-515.7272</coefficient>
				<coefficient>38.19218</coefficient>
				<coefficient>0</coefficient>
				<coefficient>0</coefficient>
			</thermalConductivity>
			<integratedThermalConductivity>
				<equationType>polyLn</equationType>
				<minTemp>88</minTemp>
				<maxTemp>300</maxTemp>
				<coefficient>-504.7463901</coefficient>
				<coefficient>933.5100236</coefficient>
				<coefficient>-734.8695628</coefficient>
				<coefficient>298.7991868</coefficient>
				<coefficient>-62.99359707</coefficient>
				<coefficient>6.393559712</coefficient>
				<coefficient>-0.809229713</coefficient>
				<coefficient>0.360706477</coefficient>
