=== fielddaylab/coolIt/server/CoolIt_Service/Schema/MathGates.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid XML Studio 1.0.8.0 (http://www.liquid-technologies.com) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="CapabilityType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="CP_VS_HEAT_LEAK_GRAPH" />
      <xs:enumeration value="ANOTHER_CAPABILITY" />
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ProblemType">
    <xs:sequence>
      <xs:element name="ProblemDescription" type="xs:string" />
      <xs:element name="CorrectAnswer" type="xs:double" />
      <xs:element name="Precision" type="xs:double" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="MathGateType">
    <xs:sequence>
      <xs:element name="Name" type="xs:string" />
      <xs:element name="ID" type="xs:positiveInteger" />
      <xs:element maxOccurs="unbounded" name="Problem" type="ProblemType" />
      <xs:element name="Capability" type="CapabilityType" />
    </xs:sequence>
  </xs:complexType>
  <xs:element name="mathGates">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="mathGate" type="MathGateType" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== fielddaylab/coolIt/server/CoolIt_Service/Data/MathGates.xml
<?xml version="1.0" encoding="UTF-8"?>
<mathGates xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="file:/C:/Projects/CoolIt/server/CoolIt_Service/Schema/MathGates.xsd">
    <mathGate>
        <Name>Level 1</Name>
		<ID>1</ID>
        <Problem>
            <ProblemDescription>
                The integral of the thermal conductivity (k_int) of structural aluminum, (6061-T6) from 20 K to 295 K is 31,322 (W/m).  If a 1.0 m long cylinder of 6061-T6 aluminum with inner and outer diameters of 0.02 m and 0.022 m respectively supports a 100 kg weight from the top cover of an evacuated vessel whose temperature is maintained at 295 K, how much cooling power is required to lower the temperature of the 100 kg weight to 20 K?
            </ProblemDescription>
            <CorrectAnswer>8.266 </CorrectAnswer>
            <Precision>0.01</Precision>
        </Problem>
        <Problem>
            <ProblemDescription>To what lower limit could the outer diameter be reduced before the cylinder would no longer support the weight?</ProblemDescription>
            <CorrectAnswer>0.02005</CorrectAnswer>
            <Precision>0.00001</Precision>
        </Problem>
        
        <Capability>CP_VS_HEAT_LEAK_GRAPH</Capability>
    </mathGate>
</mathGates>
