=== fielddaylab/coolIt/server/CoolIt_Service/Schema/Problems.xsd
<?xml version="1.0" encoding="utf-8" ?>
<!--Created with Liquid XML Studio (http://www.liquid-technologies.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="BoolOp">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LT"/>
      <xs:enumeration value="LE"/>
      <xs:enumeration value="EQ"/>
      <xs:enumeration value="GE"/>
      <xs:enumeration value="GT"/>
      <xs:enumeration value="NE"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="Value">
    <xs:annotation>
      <xs:documentation>
Units:

Strut Length: meters (m)
Strut Cross Section: square meters (m^2)
Strength: mega Pascals (mPa)
Input Power: Watts (W)
Cost: U. S. Dollars ($)
Temp: degrees K (K)
</xs:documentation>
    </xs:annotation>
    <xs:restriction base="xs:string">
      <xs:enumeration value="Strut Length"/>
      <xs:enumeration value="Strut Cross Section"/>
      <xs:enumeration value="Strength"/>
      <xs:enumeration value="Input Power"/>
      <xs:enumeration value="Cost"/>
      <xs:enumeration value="Temp"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="SupportMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="Compression"/>
      <xs:enumeration value="Tension"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:complexType name="ConstraintType">
    <xs:sequence>
      <xs:element name="Value" type="Value"/>
      <xs:element name="Op" type="BoolOp"/>
      <xs:element name="Limit" type="xs:double"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ConstraintCollectionType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="constraint" type="ConstraintType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ImageCollectionType">
    <xs:sequence>
      <xs:element name="baseURI" type="xs:anyURI"/>
      <xs:element name="intro" type="xs:anyURI"/>
      <xs:element name="success" type="xs:anyURI"/>
      <xs:element name="failPowerLimitExceeded" type="xs:anyURI"/>
      <xs:element name="failTargetTempNotMet" type="xs:anyURI"/>
      <xs:element name="failStrutBreaks" type="xs:anyURI"/>
      <xs:element name="pickerImageArray">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="baseName" type="xs:anyURI"/>
          </xs:sequence>
          <xs:attribute name="width" type="xs:nonNegativeInteger" use="required"/>
          <xs:attribute name="length" type="xs:nonNegativeInteger" use="required"/>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ProblemType">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="ID" type="xs:positiveInteger"/>
      <xs:element name="problemDescription" type="xs:string"/>
      <xs:element name="monetaryIncentive" type="xs:double"/>
      <xs:element name="heatLeak" type="xs:double"/>   
      <xs:element name="images" type="ImageCollectionType"/>
      <xs:element name="constraints" type="ConstraintCollectionType"/>
      <xs:element name="strutTypes" type="StrutTypeCollectionType"/>
      <xs:element name="coolers" type="CoolerCollectionType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="problems">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" name="problem" type="ProblemType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="StrutType">
    <xs:sequence>
      <xs:element name="ID" type="xs:positiveInteger"/>
      <xs:element name="count" type="xs:positiveInteger"></xs:element>
      <xs:element name="supportMode" type="SupportMode"/>
      <xs:element name="constraints" type="ConstraintCollectionType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="StrutTypeCollectionType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="strutType" type="StrutType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="coolerModel">
    <xs:sequence>
      <xs:element name="ID" type="xs:positiveInteger"/>
      <xs:element name="constraints" type="ConstraintCollectionType"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="CoolerCollectionType">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="cooler" type="coolerModel"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== fielddaylab/coolIt/server/CoolIt_Service/Data/Problems.xml
<?xml version="1.0" encoding="UTF-8"?>
<problems xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file://localhost/private/tmp/254/C//Projects/CoolIt/server/CoolIt_Service/Schema/Problems.xsd">
	<problem>
		<name>Minesweeper I</name>
		<ID>1</ID>
		<problemDescription>A mine sweeper being developed by the US Navy uses a Magnesium DiBoride superconducting
		magnet that must be cooled to 25 K in order to operate reliably. Power constraints on the ship limit the
		power consumed by the cryocooler to less than 20 kW. The 0.5 m diameter by 1.0 m tall magnet that weighs 2,500
		kg is to be mounted on a support cylinder inside a cylindrical vessel that has maximum inside dimensions of
		0.6 m diameter by 1.5 m length. The flexible current leads that provide electric current to the magnet add
		a constant 50-watt heat load on the cryocooler. You may design the support system as though it were under a
		pure stress load, but you need to incorporate a factor of 10 to account for the fact that the support actually has
		square corners and another factor of 10 for design safety. Determine a low cost support system for the superconducting
		magnet. The navy is offering $10,000 for a valid solution to this problem.</problemDescription>
		<monetaryIncentive>10000</monetaryIncentive>
		<heatLeak>50</heatLeak>
		<images>
			<baseURI>Minesweeper_I</baseURI>
			<intro>Intro</intro>
			<success>Success</success>
			<failPowerLimitExceeded>PowerLimitExceeded</failPowerLimitExceeded>
			<failTargetTempNotMet>TooHot</failTargetTempNotMet>
			<failStrutBreaks>StrutBreaks</failStrutBreaks>
			<pickerImageArray width="2" length="2">
				<baseName>Strut</baseName>
			</pickerImageArray>
		</images>
		<constraints>
			<constraint>
				<Value>Temp</Value>
				<Op>LE</Op>
				<Limit>25</Limit>
			</constraint>
		</constraints>
		<strutTypes>
			<strutType>
				<ID>1</ID>
				<count>1</count>
				<supportMode>Compression</supportMode>
				<constraints>
					<constraint>
						<Value>Strut Length</Value>
						<Op>GE</Op>
						<Limit>0.001</Limit>
					</constraint>
					<constraint>
						<Value>Strut Length</Value>
						<Op>LE</Op>
						<Limit>0.5</Limit>
					</constraint>
					<constraint>
						<Value>Strut Cross Section</Value>
						<Op>LE</Op>
						<Limit>0.16</Limit>
					</constraint>
					<constraint>
						<Value>Force Limit</Value>
						<Op>GE</Op>
						<Limit>2.5</Limit>
					</constraint>
				</constraints>
			</strutType>
		</strutTypes>
		<coolers>
			<cooler>
				<ID>1</ID>
				<constraints>
					<constraint>
						<Value>Input Power</Value>
						<Op>LE</Op>
						<Limit>20000</Limit>
					</constraint>
				</constraints>
			</cooler>
		</coolers>
	</problem>
    
	<problem>
		<name>Minesweeper II</name>
		<ID>5</ID>
		<problemDescription>A mine sweeper being developed by the US Navy uses a Magnesium DiBoride superconducting
		magnet that must be cooled to 100 K in order to operate reliably. Power constraints on the ship limit the
		power consumed by the cryocooler to less than 100 kW. The 0.5 m diameter by 1.0 m tall magnet that weighs
		2,500 kg is to be mounted on a support cylinder inside a cylindrical vessel that has maximum inside dimensions
		of 0.6 m diameter by 3 m length. You can ignore the heat load caused by the flexible current leads that
		provide electric current to the magnet. You may design the support system as though it were under a
		pure stress load, but you need to incorporate a factor of 10 to account for the fact that the support actually has
		square corners and another factor of 10 for design safety. Determine a low cost support system for the superconducting magnet.
		The navy is offering $5,000 for a valid solution to this problem.</problemDescription>
		<monetaryIncentive>5000</monetaryIncentive>
		<heatLeak>0</heatLeak>
		<images>
			<baseURI>Minesweeper_II</baseURI>
			<intro>Intro</intro>
			<success>Success</success>
			<failPowerLimitExceeded>PowerLimitExceeded</failPowerLimitExceeded>
			<failTargetTempNotMet>TooHot</failTargetTempNotMet>
			<failStrutBreaks>StrutBreaks</failStrutBreaks>
			<pickerImageArray width="2" length="2">
				<baseName>Strut</baseName>
			</pickerImageArray>
		</images>
		<constraints>
			<constraint>
				<Value>Temp</Value>
				<Op>LE</Op>
				<Limit>100</Limit>
			</constraint>
		</constraints>
		<strutTypes>
			<strutType>
				<ID>1</ID>
				<count>1</count>
				<supportMode>Compression</supportMode>
				<constraints>
					<constraint>
						<Value>Strut Length</Value>
						<Op>GE</Op>
						<Limit>0.01</Limit>
					</constraint>
					<constraint>
						<Value>Strut Length</Value>
						<Op>LE</Op>
						<Limit>2.0</Limit>
					</constraint>
					<constraint>
						<Value>Strut Cross Section</Value>
						<Op>LE</Op>
						<Limit>0.16</Limit>
					</constraint>
					<constraint>
						<Value>Force Limit</Value>
						<Op>GE</Op>
						<Limit>2.5</Limit>
					</constraint>
				</constraints>
			</strutType>
		</strutTypes>
		<coolers>
			<cooler>
				<ID>1</ID>
				<constraints>
					<constraint>
						<Value>Input Power</Value>
						<Op>LE</Op>
						<Limit>100000</Limit>
					</constraint>
				</constraints>
			</cooler>
		</coolers>
	</problem>
	
	<problem>
		<name>Minesweeper III</name>
		<ID>6</ID>
		<problemDescription>A mine sweeper being developed by the US Navy uses a Magnesium DiBoride superconducting
		magnet that must be cooled to 20 K in order to operate reliably. Power constraints on the ship limit the
		power consumed by the cryocooler to less than 20 kW. The 0.5 m diameter by 1.0 m tall magnet that weighs
		5,000 kg is to be mounted on 6 identical support posts inside a cylindrical vessel that has maximum inside
		dimensions of 0.6 m diameter by 1.5 m length. The flexible current leads that provide electric current to
		the magnet add a constant 50-watt heat load on the cryocooler. You may design the support system as though it were under a
		pure stress load, but you need to incorporate a factor of 10 to account for the fact that the support actually has
		square corners and another factor of 10 for design safety.  Determine a low cost support system for the
		superconducting magnet. The navy is offering $15,000 for a valid soultion to this problem.</problemDescription>
		<monetaryIncentive>15000</monetaryIncentive>
		<heatLeak>50</heatLeak>
		<images>
			<baseURI>Minesweeper_III</baseURI>
			<intro>Intro</intro>
			<success>Success</success>
			<failPowerLimitExceeded>PowerLimitExceeded</failPowerLimitExceeded>
			<failTargetTempNotMet>TooHot</failTargetTempNotMet>
			<failStrutBreaks>StrutBreaks</failStrutBreaks>
			<pickerImageArray width="2" length="2">
				<baseName>Strut</baseName>
			</pickerImageArray>
		</images>
		<constraints>
			<constraint>
				<Value>Temp</Value>
				<Op>LE</Op>
				<Limit>20</Limit>
			</constraint>
		</constraints>
		<strutTypes>
			<strutType>
				<ID>1</ID>
				<count>1</count>
				<supportMode>Compression</supportMode>		
				<constraints>
					<constraint>
						<Value>Strut Length</Value>
						<Op>GE</Op>
						<Limit>0.01</Limit>
					</constraint>
					<constraint>
						<Value>Strut Length</Value>
						<Op>LE</Op>
						<Limit>0.5</Limit>
					</constraint>
					<constraint>
						<Value>Strut Cross Section</Value>
						<Op>LE</Op>
						<Limit>0.16</Limit>
					</constraint>
					<constraint>
						<Value>Force Limit</Value>
						<Op>GE</Op>
						<Limit>5</Limit>
					</constraint>
				</constraints>
			</strutType>
		</strutTypes>
		<coolers>
			<cooler>
				<ID>1</ID>
				<constraints>
					<constraint>
						<Value>Input Power</Value>
						<Op>LE</Op>
						<Limit>20000</Limit>
					</constraint>
				</constraints>
			</cooler>
		</coolers>
	</problem>
	
	 <problem>
		<name>Space Depot (hydrogen)</name>
		<ID>2</ID>
		<problemDescription>NASA is developing a space cryogen depot for travel to Mars.
		Zero boil off dewars are a critical component in NASA's plans for a space cryogen depot.
		A zero-boil-off dewar is one for which a cryocooler intercepts the heat leak to the inner
		vessel so that no liquid cryogen boils away. As shown on the design board, a set of 8
		identical straps is used to support the inner vessel of the dewar inside its vacuum shell.
		The liquid cryogen plus the inner vessel have a combined mass of 6,500kg.
		You must allow for a 4g acceleration during lift-off and a factor of 10 for design safety.
		Determine appropriate straps (geometry and material) so that the dewar can be used
		to store liquid hydrogen at its normal boiling point of 20.3 K indefinitely.
		Note that due to the
		limitations of power generation in space, you must limit your cryocooler's input power to
		4125 Watts.</problemDescription>
		<monetaryIncentive>10000</monetaryIncentive>
	 	<heatLeak>0</heatLeak>
		<images>
			<baseURI>Depot</baseURI>
			<intro>Intro</intro>
			<success>Success</success>
			<failPowerLimitExceeded>PowerLimitExceeded</failPowerLimitExceeded>
			<failTargetTempNotMet>TooHot</failTargetTempNotMet>
			<failStrutBreaks>StrutBreaks</failStrutBreaks>
			<pickerImageArray width="2" length="2">
				<baseName>Strut</baseName>
			</pickerImageArray>
		</images>
		<constraints>
			<constraint>
				<Value>Temp</Value>
				<Op>LT</Op>
				<Limit>20.3</Limit>
			</constraint>
		</constraints>
		<strutTypes>
			<strutType>
				<ID>1</ID>
				<count>8</count>
				<supportMode>Tension</supportMode>	
				<constraints>
					<constraint>
						<Value>Strut Length</Value>
						<Op>GE</Op>
						<Limit>0.01</Limit>
					</constraint>
					<constraint>
						<Value>Strut Length</Value>
						<Op>LE</Op>
						<Limit>2.0</Limit>
					</constraint>
					<constraint>
						<Value>Force Limit</Value>
						<Op>GE</Op>
						<Limit>2.60</Limit>
					</constraint>
					<constraint>
						<Value>Strut Cross Section</Value>
						<Op>LE</Op>
						<Limit>0.32</Limit>
					</constraint>
				</constraints>
			</strutType>
		</strutTypes>
	 	<coolers>
	 		<cooler>
